spring:
  application:
    name: demoReact

  datasource:
    url: jdbc:mysql://localhost:3306/ems
    username: root
    password: secret

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
logging:
  level:
    root=DEBUG:





